services:
  pms-postgres:
    image: postgres:16-alpine
    container_name: pms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pms_db
    ports:
      - '5435:5432'
    volumes:
      - pms-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pms-postgres-data:
    driver: local
